//
// Created by morei on 4/27/2020.
//

#ifndef SCRABBLEJUNIOR_COLOR_H
#define SCRABBLEJUNIOR_COLOR_H

#include <windows.h>

#define BLACK 0
#define BLUE 1
#define GREEN 2
#define CYAN 3
#define RED 4
#define MAGENTA 5
#define BROWN 6
#define LIGHTGRAY 7
#define DARKGRAY 8
#define LIGHTBLUE 9
#define LIGHTGREEN 10
#define LIGHTCYAN 11
#define LIGHTRED 12
#define LIGHTMAGENTA 13
#define YELLOW 14
#define WHITE 15


enum ConsoleColors
{
    BlackFore   = 0,
    MaroonFore  = FOREGROUND_RED,
    GreenFore   = FOREGROUND_GREEN,
    NavyFore    = FOREGROUND_BLUE,
    TealFore    = FOREGROUND_GREEN | FOREGROUND_BLUE,
    OliveFore   = FOREGROUND_RED | FOREGROUND_GREEN,
    PurpleFore  = FOREGROUND_RED | FOREGROUND_BLUE,
    GrayFore    = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
    SilverFore  = FOREGROUND_INTENSITY,
    RedFore     = FOREGROUND_INTENSITY | FOREGROUND_RED,
    LimeFore    = FOREGROUND_INTENSITY | FOREGROUND_GREEN,
    BlueFore    = FOREGROUND_INTENSITY | FOREGROUND_BLUE,
    AquaFore    = FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE,
    YellowFore  = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN,
    FuchsiaFore = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE,
    WhiteFore   = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,

    BlackBack   = 0,
    MaroonBack  = BACKGROUND_RED,
    GreenBack   = BACKGROUND_GREEN,
    NavyBack    = BACKGROUND_BLUE,
    TealBack    = BACKGROUND_GREEN | BACKGROUND_BLUE,
    OliveBack   = BACKGROUND_RED | BACKGROUND_GREEN,
    PurpleBack  = BACKGROUND_RED | BACKGROUND_BLUE,
    GrayBack    = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
    SilverBack  = BACKGROUND_INTENSITY,
    RedBack     = BACKGROUND_INTENSITY | BACKGROUND_RED,
    LimeBack    = BACKGROUND_INTENSITY | BACKGROUND_GREEN,
    BlueBack    = BACKGROUND_INTENSITY | BACKGROUND_BLUE,
    AquaBack    = BACKGROUND_INTENSITY | BACKGROUND_GREEN | BACKGROUND_BLUE,
    YellowBack  = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN,
    FuchsiaBack = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_BLUE,
    WhiteBack   = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
};

#endif //SCRABBLEJUNIOR_COLOR_H
